# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "devops@diconium.com"
      git config --global user.name "devops"
      git checkout master
    displayName: 'set git config'

  - script: |
      git checkout master
    displayName: 'checkout master'
    condition: and(succeeded(), eq(variables.isMain, true))

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npx gh-pages -d build -m '[ci skip] Update GH page' --repo https://$(GITHUB_TOKEN)@github.com/ruben-perpetua/launchdarkly-pages-test
    displayName: 'npm deploy'
    condition: and(succeeded(), eq(variables.isMain, true))

  - task: Npm@1
    inputs:
      command: publish
      publishRegistry: useFeed
      publishFeed: RubenPerpetua/devopsFeed
    condition: and(succeeded(), eq(variables.isMain, true))
